# Generated by Django 4.1 on 2023-02-20 13:03

from django.db import migrations, models
import hofmanbotapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'CAN COOLERS'), ('2', 'CABINETS'), ('3', 'CHEST FREEZERS'), ('4', 'CHEST COOLERS'), ('5', 'CONDITIONERS'), ('6', 'CONSERVATORS'), ('7', 'COUNTER COOLERS'), ('8', 'DOOR COOLERS'), ('9', 'DISPENSERS'), ('10', 'ENERGY EFFICIENT'), ('11', 'FRONT COOLERS'), ('12', 'ICE SHOW'), ('13', 'ICE MACHINES'), ('14', 'MICRO'), ('15', 'PREMIUM COOLERS'), ('16', 'UPRIGHT FREEZERS'), ('17', 'SUB-ZERO'), ('18', 'SUPERMARKET FREEZERS'), ('19', 'SUPERMARKET COOLERS'), ('20', 'POOL TYPE'), ('21', 'WATER')], max_length=200)),
                ('product', models.CharField(max_length=200, unique=True)),
                ('img', models.ImageField(default='posts/default.jpg', upload_to=hofmanbotapp.models.upload)),
                ('description', models.TextField()),
                ('add_bot_button', models.BooleanField()),
            ],
        ),
    ]
