# Generated by Django 4.1.2 on 2022-10-31 06:02

from django.db import migrations, models
import django.db.models.deletion
import hofmanbotapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('img', models.ImageField(default='posts/default.jpg', upload_to=hofmanbotapp.models.upload)),
                ('description', models.TextField()),
                ('add_bot_button', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hofmanbotapp.category')),
            ],
        ),
    ]
