# Generated by Django 4.1.2 on 2022-10-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hofmanbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hofmanbotapp.category', verbose_name='Category.name'),
        ),
    ]
