# Generated by Django 4.1.2 on 2022-10-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hofmanbotapp', '0002_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
